#!/bin/bash

THE_ENV=$1;

if [ -z "$THE_ENV" ]; then
  THE_ENV="development";
fi

echo "$(tput setaf 2)$(tput bold)==============================================$(tput sgr0)";
echo "$(tput setaf 2)$(tput bold) Starting $(tput setaf 3)STAR SONG$(tput setaf 2) in $THE_ENV mode$(tput sgr0)";
echo "$(tput setaf 2)$(tput bold)==============================================$(tput sgr0)";

case "$THE_ENV" in
  "development" )
    export ROOT_URL='http://localhost:3000'
    export MAIL_URL='smtp://postmaster@sandbox1907b9114f414a5585e79651386efa9a.mailgun.org:73f5c5f0b91b7a0be512dbbc3e14353f@smtp.mailgun.org:587'
    meteor run --port 3000 --settings settings.json
    ;;
esac

